<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="2" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-03-16T21:48:06 IST" name="inetBankingV1" finished-at="2021-03-16T21:48:32 IST" duration-ms="26330">
    <groups>
    </groups>
    <test started-at="2021-03-16T21:48:06 IST" name="BankingApp ChromeTest" finished-at="2021-03-16T21:48:32 IST" duration-ms="26330">
      <class name="com.inetbanking.testcases.TC_LoginTest_002">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a]" started-at="2021-03-16T21:48:06 IST" name="setup" finished-at="2021-03-16T21:48:11 IST" duration-ms="5183" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a]" started-at="2021-03-16T21:48:12 IST" name="login" data-provider="LoginData" finished-at="2021-03-16T21:48:14 IST" duration-ms="2330" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr312414]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[UzYretu]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Wrong username or password]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Wrong username or password
at org.testng.Assert.fail(Assert.java:99)
at com.inetbanking.testcases.TC_LoginTest_002.login(TC_LoginTest_002.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="endResult(org.testng.ITestResult)[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a]" started-at="2021-03-16T21:48:14 IST" name="endResult" finished-at="2021-03-16T21:48:15 IST" duration-ms="362" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=TC_LoginTest_002.login(java.lang.String,java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endResult -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a]" started-at="2021-03-16T21:48:15 IST" name="login" data-provider="LoginData" finished-at="2021-03-16T21:48:18 IST" duration-ms="2867" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr312414]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[UzYregu]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="endResult(org.testng.ITestResult)[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a]" started-at="2021-03-16T21:48:18 IST" name="endResult" finished-at="2021-03-16T21:48:18 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=SUCCESS method=TC_LoginTest_002.login(java.lang.String,java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endResult -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a]" started-at="2021-03-16T21:48:18 IST" name="login" data-provider="LoginData" finished-at="2021-03-16T21:48:22 IST" duration-ms="3890" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr362414]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[UzYregu]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Wrong username or password]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Wrong username or password
at org.testng.Assert.fail(Assert.java:99)
at com.inetbanking.testcases.TC_LoginTest_002.login(TC_LoginTest_002.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="endResult(org.testng.ITestResult)[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a]" started-at="2021-03-16T21:48:22 IST" name="endResult" finished-at="2021-03-16T21:48:22 IST" duration-ms="370" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=TC_LoginTest_002.login(java.lang.String,java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endResult -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a]" started-at="2021-03-16T21:48:22 IST" name="login" data-provider="LoginData" finished-at="2021-03-16T21:48:24 IST" duration-ms="2394" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr312414]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[UzYregu]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a]" started-at="2021-03-16T21:48:24 IST" name="login" data-provider="LoginData" finished-at="2021-03-16T21:48:28 IST" duration-ms="3874" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr352414]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[UzYrbgu]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Wrong username or password]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Wrong username or password
at org.testng.Assert.fail(Assert.java:99)
at com.inetbanking.testcases.TC_LoginTest_002.login(TC_LoginTest_002.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="endResult(org.testng.ITestResult)[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a]" started-at="2021-03-16T21:48:24 IST" name="endResult" finished-at="2021-03-16T21:48:24 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=SUCCESS method=TC_LoginTest_002.login(java.lang.String,java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endResult -->
        <test-method is-config="true" signature="endResult(org.testng.ITestResult)[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a]" started-at="2021-03-16T21:48:28 IST" name="endResult" finished-at="2021-03-16T21:48:29 IST" duration-ms="378" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=TC_LoginTest_002.login(java.lang.String,java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endResult -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.inetbanking.testcases.TC_LoginTest_002@2d710f1a]" started-at="2021-03-16T21:48:29 IST" name="teardown" finished-at="2021-03-16T21:48:32 IST" duration-ms="3773" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.inetbanking.testcases.TC_LoginTest_002 -->
    </test> <!-- BankingApp ChromeTest -->
  </suite> <!-- inetBankingV1 -->
</testng-results>
